name: free-foil
version: 0.0.1
github: "fizruk/free-foil"
license: BSD3
author: "Nikolai Kudasov"
maintainer: "nickolay.kudasov@gmail.com"
copyright: "2023 Nikolai Kudasov"

extra-source-files:
  - README.md
  - LICENSE
  - grammar/LambdaPi/Simple.cf

synopsis: Efficient Type-Safe Capture-Avoiding Substitution for Free (Scoped Monads)
category: Parsing # same as BNFC

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/fizruk/free-foil#readme>

custom-setup:
  dependencies:
    base: ">= 4.11.0.0 && < 5.0"
    Cabal: ">= 2.4.0.1 && < 4.0"
    process: ">= 1.6.3.0"

build-tools:
  alex: ">= 3.2.4"
  happy: ">= 1.19.9"
  BNFC:bnfc: ">= 2.9.4.1"

dependencies:
  array: ">= 0.5.3.0"
  base: ">= 4.7 && < 5"
  text: ">= 1.2.3.1"
  containers:
  bifunctors:
  template-haskell:

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -optP-Wno-nonportable-include-path

library:
  source-dirs: src
  when:
    - condition: false
      other-modules:
        - Language.LambdaPi.Simple.Test
        - Language.LambdaPi.Simple.ErrM
        - Language.LambdaPi.Simple.Skel

executables:
  lambda-pi:
    main: LambdaPi.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil

tests:
  free-foil-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
      - base
      - doctest
      - Glob
      - QuickCheck
      - template-haskell
      - containers
