name: free-foil
version: 0.2.0
github: "fizruk/free-foil"
license: BSD3
author: "Nikolai Kudasov"
maintainer: "nickolay.kudasov@gmail.com"
copyright: "2023–2024 Nikolai Kudasov, Renata Shakirova, Egor Shalagin, Karina Tyulebaeva"

extra-source-files:
  - README.md
  - ChangeLog.md
  - LICENSE

synopsis: Efficient Type-Safe Capture-Avoiding Substitution for Free (Scoped Monads)
category: Parsing # same as BNFC

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/fizruk/free-foil#readme>

dependencies:
  array: ">= 0.5.3.0"
  base: ">= 4.7 && < 5"
  text: ">= 1.2.3.1"
  containers:
  bifunctors:
  template-haskell: ">= 2.21.0.0"
  deepseq:
  kind-generics: ">= 0.5.0"

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -optP-Wno-nonportable-include-path

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil

  doctests:
    source-dirs:
      - src/
      - test/doctests
    main: Main.hs
    other-modules: []
    dependencies:
      - free-foil
      - doctest-parallel
