// File generated by the BNF Converter (bnfc 2.9.6).

package org.syntax.lambdapi.simple;

/** All Visitor */

public interface AllVisitor<R,A> extends
  org.syntax.lambdapi.simple.Absyn.Program.Visitor<R,A>,
  org.syntax.lambdapi.simple.Absyn.Command.Visitor<R,A>,
  org.syntax.lambdapi.simple.Absyn.Term.Visitor<R,A>
{}
