-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language Syntax.

module Language.MLTT.Syntax.Abs where

import Prelude (String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Functor, Foldable, Traversable
  , Int, Maybe(..)
  )
import qualified Data.String

import qualified Data.Data    as C (Data, Typeable)
import qualified GHC.Generics as C (Generic)

type Program = Program' BNFC'Position
data Program' a = AProgram a [Module' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Typeable, C.Generic)

type Module = Module' BNFC'Position
data Module' a = AModule a VarIdent [Import' a] [Decl' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Typeable, C.Generic)

type Import = Import' BNFC'Position
data Import' a = AnImport a VarIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Typeable, C.Generic)

type Decl = Decl' BNFC'Position
data Decl' a
    = DeclDef a VarIdent (Term' a) (Term' a)
    | DeclPrivateDef a VarIdent (Term' a) (Term' a)
    | DeclNamespace a VarIdent [Decl' a]
    | DeclOpen a VarIdent
    | DeclCheck a (Term' a) (Term' a)
    | DeclCompute a (Term' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Typeable, C.Generic)

type Term = Term' BNFC'Position
data Term' a
    = Pi a (Pattern' a) (Term' a) (ScopedTerm' a)
    | Sigma a (Pattern' a) (Term' a) (ScopedTerm' a)
    | Lam a (Pattern' a) (ScopedTerm' a)
    | Let a (Pattern' a) (Term' a) (ScopedTerm' a)
    | Arrow a (Term' a) (Term' a)
    | Product a (Term' a) (Term' a)
    | App a (Term' a) (Term' a)
    | First a (Term' a)
    | Second a (Term' a)
    | Universe a
    | UnitType a
    | UnitVal a
    | Var a VarIdent
    | IdType a (Term' a) (Term' a) (Term' a)
    | Refl a (Term' a)
    | J a (Term' a) (Term' a) (Term' a)
    | Pair a (Term' a) (Term' a)
    | Ann a (Term' a) (Term' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Typeable, C.Generic)

type ScopedTerm = ScopedTerm' BNFC'Position
data ScopedTerm' a = AScopedTerm a (Term' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Typeable, C.Generic)

type Pattern = Pattern' BNFC'Position
data Pattern' a
    = PatternWildcard a
    | PatternVar a VarIdent
    | PatternPair a (Pattern' a) (Pattern' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Typeable, C.Generic)

newtype VarIdent = VarIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Program where
  hasPosition = \case
    AProgram p _ -> p

instance HasPosition Module where
  hasPosition = \case
    AModule p _ _ _ -> p

instance HasPosition Import where
  hasPosition = \case
    AnImport p _ -> p

instance HasPosition Decl where
  hasPosition = \case
    DeclDef p _ _ _ -> p
    DeclPrivateDef p _ _ _ -> p
    DeclNamespace p _ _ -> p
    DeclOpen p _ -> p
    DeclCheck p _ _ -> p
    DeclCompute p _ -> p

instance HasPosition Term where
  hasPosition = \case
    Pi p _ _ _ -> p
    Sigma p _ _ _ -> p
    Lam p _ _ -> p
    Let p _ _ _ -> p
    Arrow p _ _ -> p
    Product p _ _ -> p
    App p _ _ -> p
    First p _ -> p
    Second p _ -> p
    Universe p -> p
    UnitType p -> p
    UnitVal p -> p
    Var p _ -> p
    IdType p _ _ _ -> p
    Refl p _ -> p
    J p _ _ _ -> p
    Pair p _ _ -> p
    Ann p _ _ -> p

instance HasPosition ScopedTerm where
  hasPosition = \case
    AScopedTerm p _ -> p

instance HasPosition Pattern where
  hasPosition = \case
    PatternWildcard p -> p
    PatternVar p _ -> p
    PatternPair p _ _ -> p

