-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Language.

module Language.MLTT.Syntax.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Language.MLTT.Syntax.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Language.MLTT.Syntax.Abs.VarIdent where
  prt _ (Language.MLTT.Syntax.Abs.VarIdent i) = doc $ showString i
instance Print (Language.MLTT.Syntax.Abs.Program' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.AProgram _ units -> prPrec i 0 (concatD [prt 0 units])

instance Print [Language.MLTT.Syntax.Abs.Unit' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Language.MLTT.Syntax.Abs.Unit' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.UnitModule _ module_ -> prPrec i 0 (concatD [prt 0 module_])
    Language.MLTT.Syntax.Abs.UnitTelescope _ telescopedecl -> prPrec i 0 (concatD [prt 0 telescopedecl])

instance Print (Language.MLTT.Syntax.Abs.Module' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.AModule _ varident includes params imports decls -> prPrec i 0 (concatD [doc (showString "module"), prt 0 varident, prt 0 includes, prt 0 params, doc (showString ";"), prt 0 imports, prt 0 decls])

instance Print (Language.MLTT.Syntax.Abs.Include' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.AnInclude _ varident refinement -> prPrec i 0 (concatD [doc (showString "include"), prt 0 varident, prt 0 refinement])

instance Print [Language.MLTT.Syntax.Abs.Include' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Language.MLTT.Syntax.Abs.Refinement' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.NoRefinement _ -> prPrec i 0 (concatD [])
    Language.MLTT.Syntax.Abs.ARefinement _ fixeds -> prPrec i 0 (concatD [doc (showString "/"), doc (showString "{"), prt 0 fixeds, doc (showString "}")])

instance Print (Language.MLTT.Syntax.Abs.Fixed' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.AFixed _ varident term -> prPrec i 0 (concatD [prt 0 varident, doc (showString ":="), prt 0 term])

instance Print [Language.MLTT.Syntax.Abs.Fixed' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Language.MLTT.Syntax.Abs.TelescopeDecl' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.ATelescope _ varident params -> prPrec i 0 (concatD [doc (showString "telescope"), prt 0 varident, prt 0 params, doc (showString ";")])

instance Print (Language.MLTT.Syntax.Abs.Param' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.AParam _ varident term -> prPrec i 0 (concatD [doc (showString "("), prt 0 varident, doc (showString ":"), prt 0 term, doc (showString ")")])
    Language.MLTT.Syntax.Abs.AManifest _ varident term1 term2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 varident, doc (showString ":"), prt 0 term1, doc (showString ":="), prt 0 term2, doc (showString ")")])

instance Print [Language.MLTT.Syntax.Abs.Param' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Language.MLTT.Syntax.Abs.Import' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.AnImport _ varident -> prPrec i 0 (concatD [doc (showString "import"), prt 0 varident])

instance Print [Language.MLTT.Syntax.Abs.Import' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print (Language.MLTT.Syntax.Abs.Decl' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.DeclDef _ varident discharge term1 term2 -> prPrec i 0 (concatD [doc (showString "def"), prt 0 varident, prt 0 discharge, doc (showString ":"), prt 0 term1, doc (showString ":="), prt 0 term2])
    Language.MLTT.Syntax.Abs.DeclPrivateDef _ varident discharge term1 term2 -> prPrec i 0 (concatD [doc (showString "private"), doc (showString "def"), prt 0 varident, prt 0 discharge, doc (showString ":"), prt 0 term1, doc (showString ":="), prt 0 term2])
    Language.MLTT.Syntax.Abs.DeclNamespace _ varident decls -> prPrec i 0 (concatD [doc (showString "namespace"), prt 0 varident, doc (showString "where"), doc (showString "{"), prt 0 decls, doc (showString "}")])
    Language.MLTT.Syntax.Abs.DeclOpen _ varident -> prPrec i 0 (concatD [doc (showString "open"), prt 0 varident])
    Language.MLTT.Syntax.Abs.DeclCheck _ term1 term2 -> prPrec i 0 (concatD [doc (showString "check"), prt 0 term1, doc (showString ":"), prt 0 term2])
    Language.MLTT.Syntax.Abs.DeclCompute _ term -> prPrec i 0 (concatD [doc (showString "compute"), prt 0 term])

instance Print [Language.MLTT.Syntax.Abs.Decl' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print (Language.MLTT.Syntax.Abs.Discharge' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.NoDischarge _ -> prPrec i 0 (concatD [])
    Language.MLTT.Syntax.Abs.DischargeOver _ varidents -> prPrec i 0 (concatD [doc (showString "over"), doc (showString "("), prt 0 varidents, doc (showString ")")])

instance Print [Language.MLTT.Syntax.Abs.VarIdent] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Language.MLTT.Syntax.Abs.Term' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.Pi _ pattern_ term scopedterm -> prPrec i 0 (concatD [doc (showString "\928"), doc (showString "("), prt 0 pattern_, doc (showString ":"), prt 0 term, doc (showString ")"), doc (showString "\8594"), prt 0 scopedterm])
    Language.MLTT.Syntax.Abs.Sigma _ pattern_ term scopedterm -> prPrec i 0 (concatD [doc (showString "\931"), doc (showString "("), prt 0 pattern_, doc (showString ":"), prt 0 term, doc (showString ")"), doc (showString "\215"), prt 0 scopedterm])
    Language.MLTT.Syntax.Abs.Lam _ pattern_ scopedterm -> prPrec i 0 (concatD [doc (showString "\955"), prt 0 pattern_, doc (showString "\8658"), prt 0 scopedterm])
    Language.MLTT.Syntax.Abs.Let _ pattern_ term scopedterm -> prPrec i 0 (concatD [doc (showString "let"), prt 0 pattern_, doc (showString "="), prt 0 term, doc (showString "in"), prt 0 scopedterm])
    Language.MLTT.Syntax.Abs.Arrow _ term1 term2 -> prPrec i 0 (concatD [prt 1 term1, doc (showString "\8594"), prt 0 term2])
    Language.MLTT.Syntax.Abs.Product _ term1 term2 -> prPrec i 0 (concatD [prt 1 term1, doc (showString "\215"), prt 0 term2])
    Language.MLTT.Syntax.Abs.App _ term1 term2 -> prPrec i 1 (concatD [prt 1 term1, prt 2 term2])
    Language.MLTT.Syntax.Abs.First _ term -> prPrec i 2 (concatD [doc (showString "\960\8321"), prt 2 term])
    Language.MLTT.Syntax.Abs.Second _ term -> prPrec i 2 (concatD [doc (showString "\960\8322"), prt 2 term])
    Language.MLTT.Syntax.Abs.Universe _ -> prPrec i 2 (concatD [doc (showString "\120140")])
    Language.MLTT.Syntax.Abs.UnitType _ -> prPrec i 2 (concatD [doc (showString "\120793")])
    Language.MLTT.Syntax.Abs.UnitVal _ -> prPrec i 2 (concatD [doc (showString "tt")])
    Language.MLTT.Syntax.Abs.Var _ varident -> prPrec i 2 (concatD [prt 0 varident])
    Language.MLTT.Syntax.Abs.IdType _ term1 term2 term3 -> prPrec i 2 (concatD [doc (showString "Id"), doc (showString "("), prt 0 term1, doc (showString ","), prt 0 term2, doc (showString ","), prt 0 term3, doc (showString ")")])
    Language.MLTT.Syntax.Abs.Refl _ term -> prPrec i 2 (concatD [doc (showString "refl"), doc (showString "("), prt 0 term, doc (showString ")")])
    Language.MLTT.Syntax.Abs.J _ term1 term2 term3 -> prPrec i 2 (concatD [doc (showString "J"), doc (showString "("), prt 0 term1, doc (showString ","), prt 0 term2, doc (showString ","), prt 0 term3, doc (showString ")")])
    Language.MLTT.Syntax.Abs.Pair _ term1 term2 -> prPrec i 2 (concatD [doc (showString "("), prt 0 term1, doc (showString ","), prt 0 term2, doc (showString ")")])
    Language.MLTT.Syntax.Abs.Ann _ term1 term2 -> prPrec i 2 (concatD [doc (showString "("), prt 0 term1, doc (showString ":"), prt 0 term2, doc (showString ")")])

instance Print (Language.MLTT.Syntax.Abs.ScopedTerm' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.AScopedTerm _ term -> prPrec i 0 (concatD [prt 0 term])

instance Print (Language.MLTT.Syntax.Abs.Pattern' a) where
  prt i = \case
    Language.MLTT.Syntax.Abs.PatternWildcard _ -> prPrec i 0 (concatD [doc (showString "_")])
    Language.MLTT.Syntax.Abs.PatternVar _ varident -> prPrec i 0 (concatD [prt 0 varident])
    Language.MLTT.Syntax.Abs.PatternPair _ pattern_1 pattern_2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 pattern_1, doc (showString ","), prt 0 pattern_2, doc (showString ")")])
