-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Language.MLTT.Syntax.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Language.MLTT.Syntax.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transVarIdent :: Language.MLTT.Syntax.Abs.VarIdent -> Result
transVarIdent x = case x of
  Language.MLTT.Syntax.Abs.VarIdent string -> failure x

transProgram :: Show a => Language.MLTT.Syntax.Abs.Program' a -> Result
transProgram x = case x of
  Language.MLTT.Syntax.Abs.AProgram _ commands -> failure x

transCommand :: Show a => Language.MLTT.Syntax.Abs.Command' a -> Result
transCommand x = case x of
  Language.MLTT.Syntax.Abs.CommandCheck _ term1 term2 -> failure x
  Language.MLTT.Syntax.Abs.CommandCompute _ term -> failure x
  Language.MLTT.Syntax.Abs.CommandDef _ varident term1 term2 -> failure x

transTerm :: Show a => Language.MLTT.Syntax.Abs.Term' a -> Result
transTerm x = case x of
  Language.MLTT.Syntax.Abs.Pi _ pattern_ term scopedterm -> failure x
  Language.MLTT.Syntax.Abs.Sigma _ pattern_ term scopedterm -> failure x
  Language.MLTT.Syntax.Abs.Lam _ pattern_ scopedterm -> failure x
  Language.MLTT.Syntax.Abs.Let _ pattern_ term scopedterm -> failure x
  Language.MLTT.Syntax.Abs.Arrow _ term1 term2 -> failure x
  Language.MLTT.Syntax.Abs.Product _ term1 term2 -> failure x
  Language.MLTT.Syntax.Abs.App _ term1 term2 -> failure x
  Language.MLTT.Syntax.Abs.First _ term -> failure x
  Language.MLTT.Syntax.Abs.Second _ term -> failure x
  Language.MLTT.Syntax.Abs.Universe _ -> failure x
  Language.MLTT.Syntax.Abs.UnitType _ -> failure x
  Language.MLTT.Syntax.Abs.UnitVal _ -> failure x
  Language.MLTT.Syntax.Abs.Var _ varident -> failure x
  Language.MLTT.Syntax.Abs.IdType _ term1 term2 term3 -> failure x
  Language.MLTT.Syntax.Abs.Refl _ term -> failure x
  Language.MLTT.Syntax.Abs.J _ term1 term2 term3 -> failure x
  Language.MLTT.Syntax.Abs.Pair _ term1 term2 -> failure x
  Language.MLTT.Syntax.Abs.Ann _ term1 term2 -> failure x

transScopedTerm :: Show a => Language.MLTT.Syntax.Abs.ScopedTerm' a -> Result
transScopedTerm x = case x of
  Language.MLTT.Syntax.Abs.AScopedTerm _ term -> failure x

transPattern :: Show a => Language.MLTT.Syntax.Abs.Pattern' a -> Result
transPattern x = case x of
  Language.MLTT.Syntax.Abs.PatternWildcard _ -> failure x
  Language.MLTT.Syntax.Abs.PatternVar _ varident -> failure x
  Language.MLTT.Syntax.Abs.PatternPair _ pattern_1 pattern_2 -> failure x
