// File generated by the BNF Converter (bnfc 2.9.6).

package org.syntax.lambdapi.simple.Absyn;

public class AProgram  extends Program {
  public final ListCommand listcommand_;
  public AProgram(ListCommand p1) { listcommand_ = p1; }

  public <R,A> R accept(org.syntax.lambdapi.simple.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.lambdapi.simple.Absyn.AProgram) {
      org.syntax.lambdapi.simple.Absyn.AProgram x = (org.syntax.lambdapi.simple.Absyn.AProgram)o;
      return this.listcommand_.equals(x.listcommand_);
    }
    return false;
  }

  public int hashCode() {
    return this.listcommand_.hashCode();
  }


}
