// File generated by the BNF Converter (bnfc 2.9.6).

package org.syntax.lambdapi.simple.Absyn;

public abstract class Command implements java.io.Serializable {
  public abstract <R,A> R accept(Command.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(org.syntax.lambdapi.simple.Absyn.CommandCheck p, A arg);
    public R visit(org.syntax.lambdapi.simple.Absyn.CommandCompute p, A arg);

  }

}
