// File generated by the BNF Converter (bnfc 2.9.6).

package org.syntax.lambdapi.simple.Absyn;

public class Lam  extends Term {
  public final String ident_;
  public final Term term_;
  public Lam(String p1, Term p2) { ident_ = p1; term_ = p2; }

  public <R,A> R accept(org.syntax.lambdapi.simple.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.lambdapi.simple.Absyn.Lam) {
      org.syntax.lambdapi.simple.Absyn.Lam x = (org.syntax.lambdapi.simple.Absyn.Lam)o;
      return this.ident_.equals(x.ident_) && this.term_.equals(x.term_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.term_.hashCode();
  }


}
