// File generated by the BNF Converter (bnfc 2.9.6).

package org.syntax.lambdapi.simple.Absyn;

public class Pi  extends Term {
  public final String ident_;
  public final Term term_1, term_2;
  public Pi(String p1, Term p2, Term p3) { ident_ = p1; term_1 = p2; term_2 = p3; }

  public <R,A> R accept(org.syntax.lambdapi.simple.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.lambdapi.simple.Absyn.Pi) {
      org.syntax.lambdapi.simple.Absyn.Pi x = (org.syntax.lambdapi.simple.Absyn.Pi)o;
      return this.ident_.equals(x.ident_) && this.term_1.equals(x.term_1) && this.term_2.equals(x.term_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.term_1.hashCode())+this.term_2.hashCode();
  }


}
