// File generated by the BNF Converter (bnfc 2.9.6).

package org.syntax.lambdapi.simple.Absyn;

public abstract class Term implements java.io.Serializable {
  public abstract <R,A> R accept(Term.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(org.syntax.lambdapi.simple.Absyn.Lam p, A arg);
    public R visit(org.syntax.lambdapi.simple.Absyn.Pi p, A arg);
    public R visit(org.syntax.lambdapi.simple.Absyn.App p, A arg);
    public R visit(org.syntax.lambdapi.simple.Absyn.Var p, A arg);

  }

}
