// File generated by the BNF Converter (bnfc 2.9.6).

package org.syntax.lambdapi.simple.Absyn;

public class Var  extends Term {
  public final String ident_;
  public Var(String p1) { ident_ = p1; }

  public <R,A> R accept(org.syntax.lambdapi.simple.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.syntax.lambdapi.simple.Absyn.Var) {
      org.syntax.lambdapi.simple.Absyn.Var x = (org.syntax.lambdapi.simple.Absyn.Var)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
