-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Language.Lambda.Syntax.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Language.Lambda.Syntax.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transVarIdent :: Language.Lambda.Syntax.Abs.VarIdent -> Result
transVarIdent x = case x of
  Language.Lambda.Syntax.Abs.VarIdent string -> failure x

transProgram :: Show a => Language.Lambda.Syntax.Abs.Program' a -> Result
transProgram x = case x of
  Language.Lambda.Syntax.Abs.AProgram _ terms -> failure x

transTerm :: Show a => Language.Lambda.Syntax.Abs.Term' a -> Result
transTerm x = case x of
  Language.Lambda.Syntax.Abs.Var _ varident -> failure x
  Language.Lambda.Syntax.Abs.Lam _ pattern_ scopedterm -> failure x
  Language.Lambda.Syntax.Abs.App _ term1 term2 -> failure x

transScopedTerm :: Show a => Language.Lambda.Syntax.Abs.ScopedTerm' a -> Result
transScopedTerm x = case x of
  Language.Lambda.Syntax.Abs.AScopedTerm _ term -> failure x

transPattern :: Show a => Language.Lambda.Syntax.Abs.Pattern' a -> Result
transPattern x = case x of
  Language.Lambda.Syntax.Abs.PatternVar _ varident -> failure x
